stages:
  - test
  - linting

ruff:
  stage: linting
  image: registry.gitlab.com/pipeline-components/ruff:latest
  script:
    - ruff --format=gitlab .

mypy:
  stage: linting
  image: python:3.11
  before_script:
    - pip install mypy
  script:
    - mypy src

pytest:
  stage: test
  image: python:3.11
  services:
    - name: localstack/localstack
      alias: localstack
  variables:
    AWS_URL: "http://localstack:4566"
    AWS_ACCESS_KEY_ID: "test"
    AWS_SECRET_ACCESS_KEY: "test"
    PYTHONPATH: "src"
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    key:
      files:
        - poetry.lock
        - .gitlab-ci.yml
      prefix: ${CI_JOB_NAME}
    paths:
      - .venv
      - .cache/pip
  before_script:
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install --no-root
  script:
    - poetry run pytest -v --junitxml=report.xml --cov=src --cov-report xml --cov-report term-missing tests
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml